create table if not exists public.marcaciones_adjuntos (
  id              bigint generated by default as identity primary key,
  marcacion_id    bigint not null references public.marcaciones(id) on delete cascade,
  nombre          text,
  archivo_url     text,
  archivo_r2_key  text,
  mime_type       text,
  created_at      timestamptz not null default timezone('utc', now())
);

create index if not exists marcaciones_adjuntos_marcacion_id_idx
  on public.marcaciones_adjuntos (marcacion_id);
